% 1. Crea la parte del texto con el cero a la izquierda (ej. "R03")
nombre_rodent = sprintf('R%02d', rodent);

% 2. Genera los nombres de los archivos combinando los textos
excelFile = ['Resting_statistics_', nombre_rodent, '.xlsx'];

%%Variables a exportar
vars = {'MNN_N_rest',...
        'SDDN_N_rest',...
        'RMSSD_N_rest',...
        'LF_N_rest',...
        'HF_N_rest',...
        'TP_N_rest',...
        'LF_HF_N_rest'};

create_excel_N_seconds;