% 1. Crea la parte del texto con el cero a la izquierda (ej. "R03")
nombre_rodent = sprintf('R%02d', rodent);

% 2. Genera los nombres de los archivos combinando los textos
excelFile = ['Baseline_statistics_', nombre_rodent, '.xlsx'];

%%Variables a exportar
vars = {'MNN_N_baseline',...
        'SDDN_N_baseline',...
        'RMSSD_N_baseline',...
        'LF_N_baseline',...
        'HF_N_baseline',...
        'TP_N_baseline',...
        'LF_HF_N_baseline'};

create_excel_N_seconds;